#!/bin/bash
# Version 1

plasmoidName=$(kreadconfig --file="$PWD/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")
plasmoidName="${plasmoidName##*.}" # Strip namespace (Eg: "org.kde.plasma.")
plasmoidVersion=$(kreadconfig --file="$PWD/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Version")
rm ${plasmoidName}-v*.plasmoid
filename=${plasmoidName}-v${plasmoidVersion}.zip
zip -r $filename opaque translucent widgets ReadMe.md ThemeEditor.qml choosecolor.py colors metadata.desktop setthemecolor.py themeeditor
mv ${filename} _releases/${filename}
echo "md5: $(md5sum $filename | awk '{ print $1 }')"
echo "sha256: $(sha256sum $filename | awk '{ print $1 }')"
