#!/bin/bash
# Version 1

plasmoidName=$(kreadconfig5 --file="$PWD/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")
plasmoidName="${plasmoidName##*.}" # Strip namespace (Eg: "org.kde.plasma.")
plasmoidVersion=$(kreadconfig5 --file="$PWD/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Version")
rm ${plasmoidName}-v*.zip

filename=${plasmoidName}-v${plasmoidVersion}.zip
zip -r $filename \
	_templates \
	dialogs \
	widgets \
	colors \
	desktoptheme.py \
	metadata.desktop \
	ReadMe.md

# mv ${filename} _releases/${filename}
echo "md5: $(md5sum $filename | awk '{ print $1 }')"
echo "sha256: $(sha256sum $filename | awk '{ print $1 }')"
