#!/bin/bash

if [ -z "$(which python3)" ]; then
	sudo apt install python3
fi
if [ -z "$(which qml)" ]; then
	sudo apt install qml
fi

qml ~/.local/share/plasma/desktoptheme/breeze-alphablack/ThemeEditor.qml
