#!/bin/bash

if [ -z "$(which python3)" ]; then
	sudo apt install python3
fi
if [ -z "$(which qmlscene)" ]; then
	echo "Need to setup qmlscene (Qt)"
	exit 1
fi
qmlscene ~/.local/share/plasma/desktoptheme/breeze-alphablack/ThemeEditor.qml
